# k8s/mysql-pv.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql
spec:
  # 必須與您的 StorageClass 名稱一致
  storageClassName: ebs-gp3-fast 
  # 讀寫模式：ReadWriteOnce 表示只能被單一節點以讀寫方式掛載 (符合 MySQL 需求)
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # 請求 5GB 的儲存空間
      storage: 4Gi

